### ISSUE TITLE
orderbook does not support limit_bids, limit_asks and group parameters

### ISSUE THREAD

**Issue by dutu** [gferrin/bitfinex#12]
orderbook method does not support the parameters `limit_bids`, `limit_asks` and `group` parameters.
It is not possible to pass any parameters to orderbook method

**Comment by gferrin** [comment]
I added an options parameter to the `orderbook` method which has the three parameters you asked for. They default to 50, 50 and 1 respectively.

**Comment by dutu** [comment]
This is great.
Wouldn't be better to leave the parameters out if they are not specified (which will take the default from bitfinex site rather then you hardcoding these in the wrapper)?
