### ISSUE TITLE
wrong parameter name for `cancel_offer`

### ISSUE THREAD

**Issue by dutu** [gferrin/bitfinex#18]
[line 276](https://github.com/gferrin/bitfinex/blob/master/src/bitfinex.coffee#L276)
`order_id: offer_id` 
should be 
`offer_id: offer_id`

I have tested OK this change.

**Comment by gferrin** [comment]
Thanks. Fixed with last commit https://github.com/gferrin/bitfinex/commit/e6e6f77a62f0ad23c6b055b6c4fe6623bdc06dd4
