### ISSUE TITLE
withdraw and transfer methods

### ISSUE THREAD

**Issue by dutu** [gferrin/bitfinex#21]
Are `withdraw` and `transfer` methods working?
Can't see them in the bitfinex api documentation

**Comment by gferrin** [comment]
These are non advertised methods that must be specially requested for each API key you would like to use them with. Enable at your own risk. If you loose your enabled keys you will loose all your money.

**Comment by dutu** [comment]
Thanks for your reply. Do you perhaps know how these methods can be requested for an API key?

**Comment by dutu** [comment]
Here is the official response from Bitfinex:


We actually have 2 undocumented API calls to allow you to withdraw by API or transfer between wallets. Please go here: https://www.bitfinex.com/account/api and give us the ID (first column) of the API key you are using so we allow your key to do these calls.

Please find below the documentation to use these 2 calls:

Withdrawal by API:

POST /v1/withdraw

Parameters:
'withdraw_type' :string (can be "bitcoin", "litecoin" or "darkcoin" or "mastercoin")
'walletselected' :string (the origin of the wallet to withdraw from, can be "trading", "exchange", or "deposit")
'amount' :decimal (amount to withdraw)
'address' :address (destination address for withdrawal)


Transfer between wallets by API:

POST /v1/transfer

Parameters:
‘amount’: decimal (amount to transfer)
‘currency’: string, currency of funds to transfer
‘walletfrom’: string. Wallet to transfer from
‘walletto’: string. Wallet to transfer to
