### ISSUE TITLE
Incorrect URL for `ticker` method

### ISSUE THREAD

**Issue by dutu** [gferrin/bitfinex#9]
Incorrect URL for `ticker` method. As per official Bitfinex API documentation the correct URL is  `pubticker/`, rather than `ticker/`.
Currently the ticker method does not return `high` and `low` parameters

Now:
https://api.bitfinex.com/v1/ticker/btcusd

With correct URL:
https://api.bitfinex.com/v1/pubticker/btcusd

**Comment by dutu** [comment]
any chance to merge [this PR](https://github.com/gferrin/bitfinex/pull/10) for the fix?
thanks in advance!

**Comment by gferrin** [comment]
Merged
